services:

  db:
    image: sql:8
    environment:
      MYSQL_DATABASE: career_coach_db
      MYSQL_ROOT_PASSWORD: "@#V33n9daj19!"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml